sudo: false
language: java
jdk:
- oraclejdk8
node_js: "10.14.2"
install:
  - npm install -g snyk
cache:
  - node
  directories:
  - $HOME/.m2

env:
  - TERM=dumb
script: mvn clean test -Djenkins.version=2.7.3 -Denforcer.skip=true -B && snyk test
after_success:
  - snyk monitor
